### PR TITLE
Styling in the popup

### PR DESCRIPTION
**Pull request by rmagee88**
Adding some more structure and styling to the popup... not changing any functionality, just styling and renaming the 'clicks' portion to 'main' (since we're no longer dealing with clicks the name was irrelevant), main is where you can switch the app on/off.

### CODE REVIEW

**Comment by mrblueblue** [comment]
LGTM

**Comment by koziscool** [comment]
lgtm

**Comment by mrblueblue** [comment]
I'm going to merge this request since these changes prevent the click data from overwriting the canvas data.

**Comment by mrblueblue** [comment]
Update: have not experienced any problems with this merge. The popup is much better now!

**Pull request merged**
