### PR TITLE
Feat/Toggle Canvas Off

### PR DESCRIPTION
**Pull request by mrblueblue**
Created a script that removes canvas element from the page.

The script can be injected by either the popup or background on an user click event.

### CODE REVIEW

**Comment by wettowelreactor** [comment]
This looks like it will remove all canvas elements. We need to target our specific canvas. 

If we have the first script already inject and then inject this one the canvas will be removed but the event handlers will not which could lead to issues. Perhaps we need to refactor the original content script to have On/Off methods that add the canvas and event listeners and remove the canvas and event listeners.

**Comment by mrblueblue** [comment]
One way we could target the specific user's canvas element is to tag the element with an unique id and then use jquery to select that element and then remove it.

**Comment by wettowelreactor** [comment]
Agreed, i would just add an ID of graffiome to the canvas.

**Comment by mrblueblue** [comment]
I've added a message listener in the content script.

If a message {toggle: 'off'} is sent, then it removes the users canvas element
If a message {toggle: 'on'} is sent, then it injects a new canvas element onto the page

**Comment by rmagee88** [comment]
LGTM :+1:

**Pull request merged**
